DROP TABLE IF EXISTS books CASCADE;

DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

CREATE SEQUENCE GLOBAL_SEQ START WITH 100000;

CREATE TABLE books
(
  id INT default GLOBAL_SEQ.nextval primary key /*PRIMARY KEY DEFAULT nextval('GLOBAL_SEQ')*/,
  title VARCHAR NOT NULL,
  author VARCHAR NOT NULL,
  description VARCHAR NOT NULL
);